import { CareerFair } from "./types";

export const SEED_EVENTS: CareerFair[] = [
  {
    id: "ev-01",
    title: "Metro Career Fair — Kickoff",
    type: "Career Fair",
    date: "2026-01-15",
    location: "KLCC Convention Centre, Kuala Lumpur",
    description:
      "Talentbank opens the year with our largest general hiring fair — 60+ employers across finance, retail, and manufacturing.",
    capacity: 500,
    registered: 480,
    status: "Published",
  },
  {
    id: "ev-02",
    title: "FinTech & Banking Expo",
    type: "Tech & Engineering Expo",
    date: "2026-01-29",
    location: "Menara Maybank, Kuala Lumpur",
    description: "A focused expo for banking, payments, and financial engineering roles.",
    capacity: 250,
    registered: 250,
    status: "SoldOut",
  },
  {
    id: "ev-03",
    title: "Campus Connect: Engineering Day",
    type: "Campus Recruiting Day",
    date: "2026-02-10",
    location: "Universiti Malaya, Kuala Lumpur",
    description: "On-campus recruiting for final-year engineering students, with resume clinics running all day.",
    capacity: 400,
    registered: 210,
    status: "Published",
  },
  {
    id: "ev-04",
    title: "Women in Tech Hiring Fair",
    type: "Diversity & Inclusion Fair",
    date: "2026-02-24",
    location: "Sunway Pyramid Convention Centre",
    description: "Employers committed to closing the gender gap in technical roles.",
    capacity: 300,
    registered: 140,
    status: "Published",
  },
  {
    id: "ev-05",
    title: "Industry Night: Startups After Dark",
    type: "Industry Night",
    date: "2026-03-06",
    location: "Common Ground, Bangsar South",
    description: "An evening mixer with founders and early hires from 20 growth-stage startups.",
    capacity: 150,
    registered: 150,
    status: "SoldOut",
  },
  {
    id: "ev-06",
    title: "Regional Manufacturing Fair",
    type: "Career Fair",
    date: "2026-03-19",
    location: "MITEC, Kuala Lumpur",
    description: "Postponed due to venue renovations. A rescheduled date will be announced.",
    capacity: 600,
    registered: 90,
    status: "Cancelled",
  },
  {
    id: "ev-07",
    title: "Virtual Grad Hiring Day",
    type: "Virtual Hiring Event",
    date: "2026-04-08",
    location: "Online",
    description: "A fully remote fair for fresh graduates, with live video booths for each employer.",
    capacity: 1000,
    registered: 640,
    status: "Published",
  },
  {
    id: "ev-08",
    title: "Green Energy & Sustainability Expo",
    type: "Tech & Engineering Expo",
    date: "2026-04-22",
    location: "KLCC Convention Centre, Kuala Lumpur",
    description: "Employers hiring for solar, EV, and sustainability engineering roles.",
    capacity: 350,
    registered: 200,
    status: "Published",
  },
  {
    id: "ev-09",
    title: "Mid-Year Career Fair",
    type: "Career Fair",
    date: "2026-05-14",
    location: "MITEC, Kuala Lumpur",
    description: "Our biggest mid-year fair, spanning two halls with 80+ employers.",
    capacity: 500,
    registered: 500,
    status: "SoldOut",
  },
  {
    id: "ev-10",
    title: "Campus Connect: Business Day",
    type: "Campus Recruiting Day",
    date: "2026-05-27",
    location: "Sunway University",
    description: "On-campus recruiting for business, finance, and marketing undergraduates.",
    capacity: 300,
    registered: 80,
    status: "Published",
  },
  {
    id: "ev-11",
    title: "Inclusive Hiring Summit",
    type: "Diversity & Inclusion Fair",
    date: "2026-06-11",
    location: "Bangsar South, Kuala Lumpur",
    description: "Cancelled at the organizer's request — a replacement summit is being planned for Q3.",
    capacity: 200,
    registered: 35,
    status: "Cancelled",
  },
  {
    id: "ev-12",
    title: "Industry Night: Product & Design",
    type: "Industry Night",
    date: "2026-06-25",
    location: "WORQ Co-Space, Kuala Lumpur",
    description: "Meet product managers and designers from consumer tech companies.",
    capacity: 150,
    registered: 60,
    status: "Published",
  },
  {
    id: "ev-13",
    title: "National Tech Talent Fair",
    type: "Tech & Engineering Expo",
    date: "2026-07-16",
    location: "KLCC Convention Centre, Kuala Lumpur",
    description: "Talentbank's flagship technology fair, featuring 100+ engineering employers.",
    capacity: 700,
    registered: 690,
    status: "Published",
  },
  {
    id: "ev-14",
    title: "Virtual Career Expo: APAC",
    type: "Virtual Hiring Event",
    date: "2026-07-30",
    location: "Online",
    description: "A regional virtual fair connecting candidates across Southeast Asia with APAC employers.",
    capacity: 1200,
    registered: 450,
    status: "Published",
  },
  {
    id: "ev-15",
    title: "August Career Fair",
    type: "Career Fair",
    date: "2026-08-13",
    location: "MITEC, Kuala Lumpur",
    description: "Registration opens one month before the fair.",
    capacity: 500,
    registered: 0,
    status: "Published",
  },
  {
    id: "ev-16",
    title: "Campus Connect: Fresh Grad Day",
    type: "Campus Recruiting Day",
    date: "2026-09-09",
    location: "Universiti Malaya, Kuala Lumpur",
    description: "Aimed at graduating students within 6 months of convocation.",
    capacity: 350,
    registered: 20,
    status: "Published",
  },
  {
    id: "ev-17",
    title: "Q4 Diversity Hiring Fair",
    type: "Diversity & Inclusion Fair",
    date: "2026-10-15",
    location: "Sunway Pyramid Convention Centre",
    description: "Closing out the year with employers focused on inclusive hiring practices.",
    capacity: 300,
    registered: 10,
    status: "Published",
  },
  {
    id: "ev-18",
    title: "Year-End Mega Career Fair",
    type: "Career Fair",
    date: "2026-11-19",
    location: "KLCC Convention Centre, Kuala Lumpur",
    description: "Talentbank's largest fair of the year, closing out annual hiring drives.",
    capacity: 800,
    registered: 5,
    status: "Published",
  },
  {
    id: "ev-19",
    title: "Industry Night: Closing the Year",
    type: "Industry Night",
    date: "2026-12-04",
    location: "Common Ground, Bangsar South",
    description: "A relaxed evening mixer to close the year's hiring calendar.",
    capacity: 150,
    registered: 0,
    status: "Published",
  },
];
